# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20170828_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='src/'),
        ),
    ]
